[package]
name = "lg-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
async-trait = "0.1.61"
futures-util = "0.3.25"
hyper = { version = "0.14.23", features = ["tcp", "server", "http1"] }
ipnet = "2.7.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_yaml = "0.9.16"
tokio = { version = "1.23.0", features = ["rt", "macros", "time"] }
tokio-postgres = "0.7.7"
tokio-util = { version = "0.7.4", features = ["codec"] }
#bgpkit-parser = { version = "0.8" }
zettabgp = "0.3.0"
