[package]
name = "fernglas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
async-trait = "0.1.61"
axum = { version = "0.6.2", default-features = false, features = ["query", "http1", "tokio"] }
bitvec = "1.0.1"
futures-util = "0.3.25"
ipnet = { version = "2.7.1", features = ["serde"] }
radix_trie = "0.2.1"
rayon = "1.6.1"
regex = "1.7.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
serde_yaml = "0.9.16"
tokio = { version = "1.23.0", features = ["rt", "macros", "time"] }
tokio-postgres = "0.7.7"
tokio-stream = "0.1.11"
tokio-util = { version = "0.7.4", features = ["codec"] }
#bgpkit-parser = { version = "0.8" }
zettabgp = "0.3.0"
